In [9]:
import numpy as np

In [11]:
l = [1, 2, 3, 4, 5]
np.array(l)

array([1, 2, 3, 4, 5])

In [13]:
a =np.array(l)
type(a)

numpy.ndarray

In [14]:
l1 = [1,2,3,4,5, "SWARNAVA"]
np.array(l1)

array(['1', '2', '3', '4', '5', 'SWARNAVA'], dtype='<U21')

In [15]:
l2 = [1,2,3,4,5, "SWARNAVA", 1.5]
np.array(l2)

array(['1', '2', '3', '4', '5', 'SWARNAVA', '1.5'], dtype='<U32')

In [16]:
l3 = [[1,2,3], [4,5,6], [7,8,9]]
np.array(l3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
l4 = [1.5, 1, 2, 3, 4, 5, "SWARNAVA"]
np.array(l4)

array(['1.5', '1', '2', '3', '4', '5', 'SWARNAVA'], dtype='<U32')

In [31]:
arr = np.array(l4)
type(arr)

numpy.ndarray

In [30]:
l5 = [1.5, 1, 2, 3, 4, 5]
np.array(l5)

array([1.5, 1. , 2. , 3. , 4. , 5. ])

In [29]:
arr = np.array(l5)
type(arr)

numpy.ndarray

In [32]:
l8 = [1, 2, 3, 4, 5]
np.asarray(l8)  

array([1, 2, 3, 4, 5])

In [33]:
l9 = (1, 2, 3, 4, 5)
np.asanyarray(l9)

array([1, 2, 3, 4, 5])

In [ ]:
tuple1 = (1, 2, 3, 4, 5)
type(tuple1)

tuple

In [39]:
np.array(tuple1)

array([1, 2, 3, 4, 5])

In [43]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [44]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1 = np.fromfunction(lambda i, j: i + j, (3, 3))

In [52]:
arr1

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [53]:
arr1.ndim

2

In [54]:
arr1.size

9

In [55]:
arr1.shape

(3, 3)

In [57]:
arr2 = np.fromfunction(lambda i, j: i * j, (3, 3))

In [58]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [59]:
arr2.shape

(3, 3)

In [60]:
arr.size

7

In [61]:
arr.ndim

1

In [62]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [63]:
iterator = ((i for i in range(10)))

In [64]:
np.fromiter(iterator, float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [65]:
np.fromstring('22 23 24', sep = " ")

array([22., 23., 24.])

In [66]:
np.fromstring('1, 2, 3', sep = ",", dtype = int)

array([1, 2, 3])

In [67]:
string = "Swarnava, Das"
string.split(",")

['Swarnava', ' Das']

In [68]:
np.array(string.split(","))

array(['Swarnava', ' Das'], dtype='<U8')

In [69]:
for i in range(5):
    print(i)    

0
1
2
3
4


In [70]:
iterator = ((i for i in range(5)))
np.fromiter(iterator, float)

array([0., 1., 2., 3., 4.])

In [71]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.zeros(5, dtype = int)


array([0, 0, 0, 0, 0])

In [73]:
np.zeros(5, dtype = float)

array([0., 0., 0., 0., 0.])

In [74]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [75]:
np.ones(5, dtype = float)

array([1., 1., 1., 1., 1.])

In [77]:
np.ones((5,20))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [78]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [83]:
np.zeros((8,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [84]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [85]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
np.zeros((2,5,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [88]:
np.ones((8,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [89]:
arr3 = np.zeros((2,5))


In [90]:
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
arr3+5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [92]:
a = arr3+5

In [93]:
a*2

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [94]:
a-1

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [95]:
a/2

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

In [96]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [101]:
np.empty((3, 5))

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304]])

In [102]:
import random

In [103]:
random.choice([1, 2, 3, 4, 5])

5

In [104]:
random.choice("Swarnava")

'S'

In [105]:
random.randrange(1,10)

6

In [107]:
list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [109]:
random.shuffle(list1)

In [110]:
#random in NumPy
np.random.random_sample((3,3))

array([[0.79648285, 0.33412786, 0.80414336],
       [0.09206584, 0.98557967, 0.43948729],
       [0.79417562, 0.4416101 , 0.92452118]])

In [111]:
np.random.rand(3,3)


array([[0.77741196, 0.61196681, 0.49268103],
       [0.95040577, 0.84821473, 0.49185398],
       [0.82259227, 0.83438846, 0.22946147]])

In [112]:
np.random.randn(2,3)

array([[ 0.58368646, -1.03059022,  0.83779232],
       [ 0.66250808,  1.34905409,  2.41575101]])

In [114]:
np.random.randint(1,12, size = (3,5))

array([[ 6, 10,  2,  7,  2],
       [ 8,  3,  4,  4,  2],
       [ 3,  3,  2, 11, 10]], dtype=int32)

In [115]:
arr4 = np.random.randint(3,4, size = (3,5))
arr4

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)

In [117]:
new = arr4.reshape(5,3)

In [118]:
new

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)

In [121]:
new1 = arr4.reshape(3,-1)

In [122]:
new1

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)

In [126]:
new1.reshape(5,3,1)

array([[[3],
        [3],
        [3]],

       [[3],
        [3],
        [3]],

       [[3],
        [3],
        [3]],

       [[3],
        [3],
        [3]],

       [[3],
        [3],
        [3]]], dtype=int32)

In [10]:
arr7 = np.random.randint(1,12, size = (3,4))
arr7

array([[ 7,  2,  8, 11],
       [ 8,  4,  6,  2],
       [ 1,  9,  6,  9]], dtype=int32)

In [11]:
arr7.size

12

In [12]:
arr7.shape

(3, 4)

In [13]:
arr7.ndim

2

In [14]:
arr7[1]

array([8, 4, 6, 2], dtype=int32)

In [15]:
arr7[1][2]

np.int32(6)

In [17]:
arr7[2][1]

np.int32(9)

In [19]:
arr7[0:3, 1:3]

array([[2, 8],
       [4, 6],
       [9, 6]], dtype=int32)

In [20]:
#slicing
arr7[0:3, 1:3]

array([[2, 8],
       [4, 6],
       [9, 6]], dtype=int32)

In [25]:
arr7[0:1, 1:2]

array([[2]], dtype=int32)

In [26]:
arr7[0, [1,2]]

array([2, 8], dtype=int32)

In [33]:
#mathemtical operations in arrays
arr10 = np.random.randint(1,3, (3,3))
arr11 = np.random.randint(1,3, (3,3))


In [34]:
arr10

array([[2, 1, 2],
       [1, 2, 2],
       [2, 2, 2]], dtype=int32)

In [35]:

arr11

array([[2, 2, 1],
       [2, 1, 1],
       [1, 1, 1]], dtype=int32)

In [36]:
arr10+arr11

array([[4, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)

In [37]:
arr10-arr11

array([[ 0, -1,  1],
       [-1,  1,  1],
       [ 1,  1,  1]], dtype=int32)

In [38]:
arr10*arr11

array([[4, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [39]:
arr10/arr11

array([[1. , 0.5, 2. ],
       [0.5, 2. , 2. ],
       [2. , 2. , 2. ]])

In [41]:
arr12 = np.random.randint(1,3, (3,3))
arr12

array([[1, 2, 2],
       [1, 2, 2],
       [2, 1, 2]], dtype=int32)

In [45]:
b = arr12+12
b

array([[13, 14, 14],
       [13, 14, 14],
       [14, 13, 14]], dtype=int32)

In [46]:
b.T

array([[13, 13, 14],
       [14, 14, 13],
       [14, 14, 14]], dtype=int32)

In [3]:
import numpy as np

In [12]:
num1 = np.random.randint(1,10, (3,5))
num2 = np.random.randint(1,10, (3,5))

In [14]:
num1

array([[4, 2, 1, 2, 1],
       [9, 2, 4, 8, 2],
       [2, 9, 2, 5, 1]], dtype=int32)

In [13]:
num2

array([[5, 7, 1, 9, 2],
       [9, 1, 1, 5, 4],
       [3, 9, 3, 7, 7]], dtype=int32)

In [15]:
num1+num2

array([[ 9,  9,  2, 11,  3],
       [18,  3,  5, 13,  6],
       [ 5, 18,  5, 12,  8]], dtype=int32)

In [17]:
b = num1*num2
b

array([[20, 14,  1, 18,  2],
       [81,  2,  4, 40,  8],
       [ 6, 81,  6, 35,  7]], dtype=int32)

In [18]:
b-num1

array([[16, 12,  0, 16,  1],
       [72,  0,  0, 32,  6],
       [ 4, 72,  4, 30,  6]], dtype=int32)

In [19]:
b.T

array([[20, 81,  6],
       [14,  2, 81],
       [ 1,  4,  6],
       [18, 40, 35],
       [ 2,  8,  7]], dtype=int32)

In [22]:
b.ndim

2

In [23]:
b.size

15

In [24]:
b.shape

(3, 5)

In [7]:
import numpy as np
arr14 = np.array((3,4))
arr14

array([3, 4])

In [8]:
arr14.expand_dims(arr14, axis = 0)

AttributeError: 'numpy.ndarray' object has no attribute 'expand_dims'

In [ ]:
arr14.expand_dims(arr14, axis = 1)

In [9]:
d = np.array([[1], [2], [3]])
d

array([[1],
       [2],
       [3]])

In [10]:
np.squeeze(d)

array([1, 2, 3])

In [11]:
np.repeat(d, 2)

array([1, 1, 2, 2, 3, 3])

In [12]:
np.repeat(d, 2, axis = 0)#repeat the elements in the array along the rows

array([[1],
       [1],
       [2],
       [2],
       [3],
       [3]])

In [13]:
np.repeat(d, 2, axis = 1)#repeat the elements in the array along the columns


array([[1, 1],
       [2, 2],
       [3, 3]])

In [14]:
e = np.array([[1],[2],[3]])
e

array([[1],
       [2],
       [3]])

In [15]:
np.roll(e, 2)


array([[2],
       [3],
       [1]])

In [16]:
np.roll(e, 1, axis = 0)

array([[3],
       [1],
       [2]])

In [17]:
f = np.array([[1,2,3],[4,5,6],[7,8,9]])
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.roll(f, 1, axis = 0)

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [19]:
np.roll(f, 2, axis = 1)

array([[2, 3, 1],
       [5, 6, 4],
       [8, 9, 7]])

In [20]:
import numpy as np
arr15 = np.array(["Swarnava", "Das"])
arr15


array(['Swarnava', 'Das'], dtype='<U8')

In [21]:
np.char.upper(arr15)

array(['SWARNAVA', 'DAS'], dtype='<U8')

In [22]:
np.char.capitalize(arr15)

array(['Swarnava', 'Das'], dtype='<U8')

In [23]:
arr16 = np.array(["SWARN", '"kumar'])
np.char.lower(arr16)

array(['swarn', '"kumar'], dtype='<U6')

In [25]:
np.char.capitalize(arr16)

array(['Swarn', '"kumar'], dtype='<U6')

In [26]:
np.char.upper(arr16)

array(['SWARN', '"KUMAR'], dtype='<U6')

In [5]:
#mathematical functions in NumPy
import numpy as np
arr17 = np.array([[3, 4], [5, 6]])

In [6]:
arr17

array([[3, 4],
       [5, 6]])

In [7]:
np.sin(arr17)

array([[ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

In [8]:
np.cos(arr17)

array([[-0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029]])

In [9]:
np.tan(arr17)

array([[-0.14254654,  1.15782128],
       [-3.38051501, -0.29100619]])

In [11]:
np.power(arr17, 2)

array([[ 9, 16],
       [25, 36]])

In [12]:
np.exp(arr17)

array([[ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

In [13]:
np.log10(arr17)

array([[0.47712125, 0.60205999],
       [0.69897   , 0.77815125]])

In [14]:
np.max(arr17)

np.int64(6)

In [15]:
np.min(arr17)

np.int64(3)

In [17]:
np.mean(arr17)

np.float64(4.5)

In [18]:
arr18 = np.array([[1, 2], [3, 4]])
arr19 = np.array([[5, 6], [7, 8]])

In [20]:
arr18

array([[1, 2],
       [3, 4]])

In [21]:
arr19

array([[5, 6],
       [7, 8]])

In [22]:
np.add(arr18, arr19)

array([[ 6,  8],
       [10, 12]])

In [23]:
np.subtract(arr18, arr19)

array([[-4, -4],
       [-4, -4]])

In [24]:
np.multiply(arr18, arr19)

array([[ 5, 12],
       [21, 32]])

In [25]:
np.divide(arr18, arr19) 

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [29]:
np.mod(arr18, arr19)

array([[1, 2],
       [3, 4]])

In [34]:
arr20 = np.array([92, 30, 10])

In [35]:
arr20

array([92, 30, 10])

In [36]:
np.sort(arr20)

array([10, 30, 92])

In [37]:
np.searchsorted(arr20, 30)

np.int64(0)

In [38]:
np.count_nonzero(arr20)

np.int64(3)

In [39]:
np.where(arr20 > 0)

(array([0, 1, 2]),)

In [40]:
arr20.byteswap()

array([6629298651489370112, 2161727821137838080,  720575940379279360])

In [41]:
#matrix operations in NumPy
import numpy.matlib as nm

In [42]:
nm.zeros(7)

matrix([[0., 0., 0., 0., 0., 0., 0.]])

In [43]:
nm.ones(4)

matrix([[1., 1., 1., 1.]])

In [45]:
arr17

array([[3, 4],
       [5, 6]])

In [46]:
arr18

array([[1, 2],
       [3, 4]])

In [47]:
arr17 @ arr18   

array([[15, 22],
       [23, 34]])